FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -B -pl erp-auth-server -am clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/erp-auth-server/target/erp-auth-server-1.0.0.jar /app/erp-auth-server.jar
EXPOSE 9000
ENTRYPOINT ["java","-jar","/app/erp-auth-server.jar"]
