FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -B -pl erp-enterprise-app -am clean package -DskipTests

FROM payara/server-full:6.2025.1-jdk21
COPY --from=build /root/.m2/repository/org/postgresql/postgresql/*/postgresql-*.jar /opt/payara/appserver/glassfish/domains/domain1/lib/postgresql.jar
COPY post-boot-commands.asadmin /opt/payara/config/post-boot-commands.asadmin
COPY --from=build /workspace/erp-enterprise-app/target/erp-enterprise-app-1.0.0.ear /opt/payara/deployments/erp-enterprise-app.ear
EXPOSE 8080 4848
